import type { Metadata } from "next";
import "./globals.css";
import { robotoMono, dmMono } from "@/utils/fonts";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmMono.className+' h-screen flex flex-col flex-1'} >
        <Header/>
        <main className="h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
